<?php

return array(
    'arbitration',
    'competition/antitrust',
    'construction litigation',
    'conveyancing',
    'derivatives',
    'ediscovery',
    'education',
    'employment (employee)',
    'employment (employer)',
    'energy',
    'funds',
    'human rights',
    'immigration (corporate)',
    'in-house',
    'insolvency',
    'insurance',
    'pensions & benefits',
    'private client (tax & trusts)',
    'private client (wills & probate)',
    'private practice',
    'product liability',
    'professional risk',
    'public law/public sector',
    'regulatory',
    'reinsurance',
    'residential property',
    'restructuring',
    'ship finance',
    'shipping litigation',
    'social housing',
    'structured products',
    'technology & media',
    'travel and tourism',
    'white-collar crime/fraud'

);
