<?php

return [
    'Magic Circle'     => 'Magic Circle',
    'Silver Circle'    => 'Silver Circle',
    'Top 50 UK Firms'  => 'Top 50 UK Firms',
    'Top 20 US Firms'  => 'Top 20 US Firms',
    'Top 100 UK Firms' => 'Top 100 UK Firms',
    'US Firms (All)'   => 'All US Firms',

    'Commercial Contracts'             => 'Top Ranked for Commercial Contracts',
    'Corporate Tax'                    => 'Top Ranked for Corporate Tax',
    'EU and Competition'               => 'Top Ranked for EU & Competition',
    'Equity - Capital Markets'         => 'Top Ranked for Equity Capital Markets',
    'Financial Services (Regulatory)'  => 'Top Ranked for Financial Services (Regulatory)',
    'Investment: Hedge Funds'          => 'Top Ranked for Investment: Hedge Funds',
    'M&A £250m+'                       => 'Top Ranked for M&A £250m+',
    'M&A £50 - £250m'                  => 'Top Ranked for M&A £50m-£250m',
    'M&A  up to £50m'                  => 'Top Ranked for M&A up to £50m',
    'Partnership'                      => 'Top Ranked for Partnership',
    'Private Equity: Large-Cap'        => 'Top Ranked for Private Equity: Large-Cap',
    'VAT & Indirect Tax'               => 'Top Ranked for VAT & Indirect Tax',
    'Venture Capital'                  => 'Top Ranked for Venture Capital',
    'Flotations: Small & Mid-Cap'      => 'Top Ranked for Flotations: Small & Mid-Cap',
    'Investment: Listed Funds'         => 'Top Ranked for Investment: Listed Funds',
    'Investment: Private Funds'        => 'Top Ranked for Investment: Private Funds',
    'Investment: Real Estate Funds'    => 'Top Ranked for Investment: Real Estate Funds',
    'Investment: Retail Funds'         => 'Top Ranked for Investment: Retail Funds',
    'Financial Services (Contentious)' => 'Top Ranked for Financial Services (Contentious)',
    'Private Equity: Mid-Cap'          => 'Top Ranked for Private Equity: Mid-Cap',

    'Corporate Crime'           => 'Top Ranked for Corporate Crime',
    'Crime: General'            => 'Top Ranked for Crime: General',
    'Fraud: Civil'              => 'Top Ranked for Fraud: Civil',
    'Fraud: White-collar Crime' => 'Top Ranked for Fraud: White-Collar Crime',
    'Gaming & Betting'          => 'Top Ranked for Gaming & Betting',
    'Licensing'                 => 'Top Ranked for Licensing',

    'Banking Litigation'              => 'Top Ranked for Banking Litigation',
    'Commercial Litigation'           => 'Top Ranked for Commercial Litigation',
    'Competition Litigation'          => 'Top Ranked for Competition Litigation',
    'Debt Recovery'                   => 'Top Ranked for Debt Recovery',
    'Reputation Management'           => 'Top Ranked for Reputation Management',
    'International Arbitration'       => 'Top Ranked for International Arbitration',
    'Public International Law'        => 'Top Ranked for Public International Law',
    'Tax Litigation & Investigations' => 'Top Ranked for Tax Litigation & Investigations',
    'Professional Discipline'         => 'Top Ranked for Professional Discipline',

    'Acquistion Finance'                   => 'Top Ranked for Acquisition Finance',
    'Asset-based Lending'                  => 'Top Ranked for Asset-based Lending',
    'Asset Finance & Leasing'              => 'Top Ranked for Asset Finance & Leasing',
    'Bank Lending'                         => 'Top Ranked for Bank Lending',
    'Commodities: Derivatives'             => 'Top Ranked for Commodities: Derivatives',
    'Commodities: Physicals'               => 'Top Ranked for Commodities: Physicals',
    'Corporate Restructuring & Insolvency' => 'Top Ranked for Corporate Restructuring & Insolvency',
    'Debt Capital Markets'                 => 'Top Ranked for Debt Capital Markets',
    'Derivatives & Structured Products'    => 'Top Ranked for Derivatives & Structured Products',
    'Islamic Finance'                      => 'Top Ranked for Islamic Finance',
    'Securitisation'                       => 'Top Ranked for Securitisation',
    'Trade Finance'                        => 'Top Ranked for Trade Finance',
    'Emerging Markets'                     => 'Top Ranked for Emerging Markets',
    'High Yield'                           => 'Top Ranked for High Yield',

    'Employee Share Schemes'        => 'Top Ranked for Employee Share Schemes',
    'Employment: Employers'         => 'Top Ranked for Employment: Employers',
    'Employment: Senior Executives' => 'Top Ranked for Employment: Senior Executives',
    'Employment: Employees/Unions'  => 'Top Ranked for Employment: Employees/Unions',
    'Health & Safety'               => 'Top Ranked for Health & Safety',
    'Immigration (Corporate)'       => 'Top Ranked for Immigration (Corporate)',
    'Pensions (Non-Contentious)'    => 'Top Ranked for Pensions (Non-Contentious)',
    'Immigration (Human Rights)'    => 'Top Ranked for Immigration (Human Rights)',
    'Pensions (Litigation)'         => 'Top Ranked for Pensions (Litigation)',


    'Clinical Negligence: Claimant'         => 'Top Ranked for Clinical Negligence: Claimant',
    'Clinical Negligence: Defendant'        => 'Top Ranked for Clinical Negligence: Defendant',
    'Insurance: Corporate & Regulatory'     => 'Top Ranked for Insurance: Corporate & Regulatory',
    'Insurance: Insolvency & Restructuring' => 'Top Ranked for Insurance: Insolvency & Restructuring',
    'Insurance Litigation: Policyholders'   => 'Top Ranked for Insurance Litigation: Policyholders',
    'Insurance & Reinsurance Litigation'    => 'Top Ranked for Insurance & Reinsurance Litigation',
    'Personal Injury: Claimant'             => 'Top Ranked for Personal Injury: Claimant',
    'Personal Injury: Defendant'            => 'Top Ranked for Personal Injury: Defendant',
    'Product Liability: Claimant'           => 'Top Ranked for Product Liability: Claimant',
    'Product Liability: Defendant'          => 'Top Ranked for Product Liability: Defendant',
    'Professional Negligence'               => 'Top Ranked for Professional Negligence',

    'Agriculture & Estates'         => 'Top Ranked for Agriculture & Estates',
    'Art & Cultural Property'       => 'Top Ranked for Art & Cultural Property',
    'Charities'                     => 'Top Ranked for Charities',
    'Contentious Trust & Probate'   => 'Top Ranked for Contentious Trust & Probate',
    'Court of Protection'           => 'Top Ranked for Court of Protection',
    'Family'                        => 'Top Ranked for Family',
    'Family: Mediation'             => 'Top Ranked for Family: Mediation',
    'Personal Tax, Trust & Probate' => 'Top Ranked for Personal Tax, Trust & Probate',

    'Infrastructure (including PFI & PPP)' => 'Top Ranked for Infrastructure (including PFI & PPP)',
    'Mining & Minerals'                    => 'Top Ranked for Mining & Minerals',
    'Oil & Gas'                            => 'Top Ranked for Oil & Gas',
    'Power'                                => 'Top Ranked for Power',
    'Water'                                => 'Top Ranked for Water',

    'Administrative & Public Law'    => 'Top Ranked for Administrative & Public Law',
    'Civil Liberties & Human Rights' => 'Top Ranked for Civil Liberties & Human Rights',
    'Education: Individuals'         => 'Top Ranked for Education: Individuals',
    'Education: Institutions'        => 'Top Ranked for Education: Institutions',
    'Education: Schools'             => 'Top Ranked for Education: Schools',
    'Electoral'                      => 'Top Ranked for Electoral',
    'Healthcare'                     => 'Top Ranked for Healthcare',
    'Infrastructure (Parliamentary)' => 'Top Ranked for Infrastructure (Parliamentary)',
    'Local Government'               => 'Top Ranked for Local Government',

    'Commercial Property'                                      => 'Top Ranked for Commercial Property',
    'Construction (Contentious)'                               => 'Top Ranked for Construction (Contentious)',
    'Development'                                              => 'Top Ranked for Development',
    'Environment'                                              => 'Top Ranked for Environment',
    'Planning'                                                 => 'Top Ranked for Planning',
    'Property Finance'                                         => 'Top Ranked for Property Finance',
    'Property Litigation'                                      => 'Top Ranked for Property Litigation',
    'Social Housing: Finance'                                  => 'Top Ranked for Social Housing: Finance',
    'Social Housing: Local Authorities & Registered Providers' => 'Top Ranked for Social Housing: Local Authorities & Registered Providers',
    'Social Housing: Tenant'                                   => 'Top Ranked for Social Housing: Tenant',
    'Construction (Non-Contentious)'                           => 'Top Ranked for Construction (Non-Contentious)',
    'Investment'                                               => 'Top Ranked for Investment',

    'Brand Management'                => 'Top Ranked for Brand Management',
    'Data Protection'                 => 'Top Ranked for Data Protection',
    'Franchising'                     => 'Top Ranked for Franchising',
    'IT & Telecoms'                   => 'Top Ranked for IT & Telecoms',
    'Intellectual Property'           => 'Top Ranked for Intellectual Property',
    'Media & Entertainment'           => 'Top Ranked for Media & Entertainment',
    'Media Finance'                   => 'Top Ranked for Media Finance',
    'Pharmaceuticals & Biotechnology' => 'Top Ranked for Pharamaceuticals & Biotechnology',
    'Sport'                           => 'Top Ranked for Sport',

    'Aviation' => 'Top Ranked for Aviation',
    'Rail'     => 'Top Ranked for Rail',
    'Shipping' => 'Top Ranked for Shipping',
    'Travel'   => 'Top Ranked for Travel',

    'Top 200 UK Firms'                        => 'Top 200 UK Firms',
    '30 Largest National Firms'               => '30 Largest National Firms',
    'Recognised Leader in East Anglia'        => 'Recognised Leader in East Anglia',
    'Recognised Leader in the East Midlands'  => 'Recognised Leader in the East Midlands',
    'Recognised Leader in the North'          => 'Recognised Leader in the North',
    'Recognised Leader in the North West'     => 'Recognised Leader in the North West',
    'Recognised Leader in the South East'     => 'Recognised Leader in the South East',
    'Recognised Leader in the South West'     => 'Recognised Leader in the South West',
    'Recognised Leader in Wales'              => 'Recognised Leader in Wales',
    'Recognised Leader in the West Midlands'  => 'Recognised Leader in the West Midlands',
    'Recognised Leader in Yorkshire & Humber' => 'Recognised Leader in Yorkshire & Humber',
];
